<?php

/**
 * BaseResponsavel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $dataObito
 * @property string $endLogradouro
 * @property string $endNumero
 * @property string $endComplemento
 * @property string $endBairro
 * @property string $endCidade
 * @property enum $endEstado
 * @property string $endCep
 * @property string $contatos
 * @property enum $autorizacaoVisita
 * @property string $observacao
 * @property Doctrine_Collection $AcolhidoResponsavel
 * @property Doctrine_Collection $EntradasESaidasResponsavel
 * 
 * @method date                getDataObito()                  Returns the current record's "dataObito" value
 * @method string              getEndLogradouro()              Returns the current record's "endLogradouro" value
 * @method string              getEndNumero()                  Returns the current record's "endNumero" value
 * @method string              getEndComplemento()             Returns the current record's "endComplemento" value
 * @method string              getEndBairro()                  Returns the current record's "endBairro" value
 * @method string              getEndCidade()                  Returns the current record's "endCidade" value
 * @method enum                getEndEstado()                  Returns the current record's "endEstado" value
 * @method string              getEndCep()                     Returns the current record's "endCep" value
 * @method string              getContatos()                   Returns the current record's "contatos" value
 * @method enum                getAutorizacaoVisita()          Returns the current record's "autorizacaoVisita" value
 * @method string              getObservacao()                 Returns the current record's "observacao" value
 * @method Doctrine_Collection getAcolhidoResponsavel()        Returns the current record's "AcolhidoResponsavel" collection
 * @method Doctrine_Collection getEntradasESaidasResponsavel() Returns the current record's "EntradasESaidasResponsavel" collection
 * @method Responsavel         setDataObito()                  Sets the current record's "dataObito" value
 * @method Responsavel         setEndLogradouro()              Sets the current record's "endLogradouro" value
 * @method Responsavel         setEndNumero()                  Sets the current record's "endNumero" value
 * @method Responsavel         setEndComplemento()             Sets the current record's "endComplemento" value
 * @method Responsavel         setEndBairro()                  Sets the current record's "endBairro" value
 * @method Responsavel         setEndCidade()                  Sets the current record's "endCidade" value
 * @method Responsavel         setEndEstado()                  Sets the current record's "endEstado" value
 * @method Responsavel         setEndCep()                     Sets the current record's "endCep" value
 * @method Responsavel         setContatos()                   Sets the current record's "contatos" value
 * @method Responsavel         setAutorizacaoVisita()          Sets the current record's "autorizacaoVisita" value
 * @method Responsavel         setObservacao()                 Sets the current record's "observacao" value
 * @method Responsavel         setAcolhidoResponsavel()        Sets the current record's "AcolhidoResponsavel" collection
 * @method Responsavel         setEntradasESaidasResponsavel() Sets the current record's "EntradasESaidasResponsavel" collection
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Luiz Oliveira
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResponsavel extends Pessoa
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('responsavel');
        $this->hasColumn('dataObito', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('endLogradouro', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('endNumero', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('endComplemento', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('endBairro', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('endCidade', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('endEstado', 'enum', 2, array(
             'type' => 'enum',
             'length' => 2,
             'values' => 
             array(
              0 => 'AC',
              1 => 'AL',
              2 => 'AP',
              3 => 'AM',
              4 => 'BA',
              5 => 'CE',
              6 => 'DF',
              7 => 'GO',
              8 => 'ES',
              9 => 'MA',
              10 => 'MT',
              11 => 'MS',
              12 => 'MG',
              13 => 'PA',
              14 => 'PB',
              15 => 'PR',
              16 => 'PE',
              17 => 'PI',
              18 => 'RJ',
              19 => 'RN',
              20 => 'RS',
              21 => 'RO',
              22 => 'RR',
              23 => 'SP',
              24 => 'SC',
              25 => 'SE',
              26 => 'TO',
             ),
             'default' => 'RJ',
             'notnull' => true,
             ));
        $this->hasColumn('endCep', 'string', 9, array(
             'type' => 'string',
             'length' => 9,
             ));
        $this->hasColumn('contatos', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('autorizacaoVisita', 'enum', 3, array(
             'type' => 'enum',
             'length' => 3,
             'values' => 
             array(
              0 => 'Sim',
              1 => 'Não',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('observacao', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Acolhido as AcolhidoResponsavel', array(
             'local' => 'id',
             'foreign' => 'responsavel_id'));

        $this->hasMany('EntradasESaidasAcolhido as EntradasESaidasResponsavel', array(
             'local' => 'id',
             'foreign' => 'responsavel_id'));
    }
}