<?php

/**
 * BaseApadrinhamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $acolhido_id
 * @property integer $padrinho_id
 * @property date $dataInicio
 * @property date $dataFim
 * @property string $observacoes
 * @property Acolhido $Acolhido
 * @property Padrinho $Padrinho
 * 
 * @method integer        getAcolhidoId()  Returns the current record's "acolhido_id" value
 * @method integer        getPadrinhoId()  Returns the current record's "padrinho_id" value
 * @method date           getDataInicio()  Returns the current record's "dataInicio" value
 * @method date           getDataFim()     Returns the current record's "dataFim" value
 * @method string         getObservacoes() Returns the current record's "observacoes" value
 * @method Acolhido       getAcolhido()    Returns the current record's "Acolhido" value
 * @method Padrinho       getPadrinho()    Returns the current record's "Padrinho" value
 * @method Apadrinhamento setAcolhidoId()  Sets the current record's "acolhido_id" value
 * @method Apadrinhamento setPadrinhoId()  Sets the current record's "padrinho_id" value
 * @method Apadrinhamento setDataInicio()  Sets the current record's "dataInicio" value
 * @method Apadrinhamento setDataFim()     Sets the current record's "dataFim" value
 * @method Apadrinhamento setObservacoes() Sets the current record's "observacoes" value
 * @method Apadrinhamento setAcolhido()    Sets the current record's "Acolhido" value
 * @method Apadrinhamento setPadrinho()    Sets the current record's "Padrinho" value
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Luiz Oliveira
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApadrinhamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('apadrinhamento');
        $this->hasColumn('acolhido_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('padrinho_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('dataInicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('dataFim', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('observacoes', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Acolhido', array(
             'local' => 'acolhido_id',
             'foreign' => 'id'));

        $this->hasOne('Padrinho', array(
             'local' => 'padrinho_id',
             'foreign' => 'id'));
    }
}