<?php

/**
 * BaseMae
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $AcolhidoMae
 * @property Doctrine_Collection $EntradasESaidasMae
 * 
 * @method Doctrine_Collection getAcolhidoMae()        Returns the current record's "AcolhidoMae" collection
 * @method Doctrine_Collection getEntradasESaidasMae() Returns the current record's "EntradasESaidasMae" collection
 * @method Mae                 setAcolhidoMae()        Sets the current record's "AcolhidoMae" collection
 * @method Mae                 setEntradasESaidasMae() Sets the current record's "EntradasESaidasMae" collection
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Luiz Oliveira
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMae extends Responsavel
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Acolhido as AcolhidoMae', array(
             'local' => 'id',
             'foreign' => 'mae_id'));

        $this->hasMany('EntradasESaidasAcolhido as EntradasESaidasMae', array(
             'local' => 'id',
             'foreign' => 'mae_id'));
    }
}