<?php

/**
 * BaseEntradasESaidasAcolhido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $acolhido_id
 * @property integer $mae_id
 * @property integer $pai_id
 * @property integer $responsavel_id
 * @property integer $voluntario_id
 * @property integer $padrinho_id
 * @property timestamp $dataSaida
 * @property timestamp $dataPrevistaRetorno
 * @property timestamp $dataRetorno
 * @property string $observacoes
 * @property Acolhido $Acolhido
 * @property Pai $Pai
 * @property Mae $Mae
 * @property Responsavel $Responsavel
 * @property Voluntario $Voluntario
 * @property Padrinho $Padrinho
 * 
 * @method integer                 getAcolhidoId()          Returns the current record's "acolhido_id" value
 * @method integer                 getMaeId()               Returns the current record's "mae_id" value
 * @method integer                 getPaiId()               Returns the current record's "pai_id" value
 * @method integer                 getResponsavelId()       Returns the current record's "responsavel_id" value
 * @method integer                 getVoluntarioId()        Returns the current record's "voluntario_id" value
 * @method integer                 getPadrinhoId()          Returns the current record's "padrinho_id" value
 * @method timestamp               getDataSaida()           Returns the current record's "dataSaida" value
 * @method timestamp               getDataPrevistaRetorno() Returns the current record's "dataPrevistaRetorno" value
 * @method timestamp               getDataRetorno()         Returns the current record's "dataRetorno" value
 * @method string                  getObservacoes()         Returns the current record's "observacoes" value
 * @method Acolhido                getAcolhido()            Returns the current record's "Acolhido" value
 * @method Pai                     getPai()                 Returns the current record's "Pai" value
 * @method Mae                     getMae()                 Returns the current record's "Mae" value
 * @method Responsavel             getResponsavel()         Returns the current record's "Responsavel" value
 * @method Voluntario              getVoluntario()          Returns the current record's "Voluntario" value
 * @method Padrinho                getPadrinho()            Returns the current record's "Padrinho" value
 * @method EntradasESaidasAcolhido setAcolhidoId()          Sets the current record's "acolhido_id" value
 * @method EntradasESaidasAcolhido setMaeId()               Sets the current record's "mae_id" value
 * @method EntradasESaidasAcolhido setPaiId()               Sets the current record's "pai_id" value
 * @method EntradasESaidasAcolhido setResponsavelId()       Sets the current record's "responsavel_id" value
 * @method EntradasESaidasAcolhido setVoluntarioId()        Sets the current record's "voluntario_id" value
 * @method EntradasESaidasAcolhido setPadrinhoId()          Sets the current record's "padrinho_id" value
 * @method EntradasESaidasAcolhido setDataSaida()           Sets the current record's "dataSaida" value
 * @method EntradasESaidasAcolhido setDataPrevistaRetorno() Sets the current record's "dataPrevistaRetorno" value
 * @method EntradasESaidasAcolhido setDataRetorno()         Sets the current record's "dataRetorno" value
 * @method EntradasESaidasAcolhido setObservacoes()         Sets the current record's "observacoes" value
 * @method EntradasESaidasAcolhido setAcolhido()            Sets the current record's "Acolhido" value
 * @method EntradasESaidasAcolhido setPai()                 Sets the current record's "Pai" value
 * @method EntradasESaidasAcolhido setMae()                 Sets the current record's "Mae" value
 * @method EntradasESaidasAcolhido setResponsavel()         Sets the current record's "Responsavel" value
 * @method EntradasESaidasAcolhido setVoluntario()          Sets the current record's "Voluntario" value
 * @method EntradasESaidasAcolhido setPadrinho()            Sets the current record's "Padrinho" value
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Luiz Oliveira
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntradasESaidasAcolhido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entradas_e_saidas_acolhido');
        $this->hasColumn('acolhido_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mae_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pai_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('responsavel_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('voluntario_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('padrinho_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dataSaida', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('dataPrevistaRetorno', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('dataRetorno', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('observacoes', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Acolhido', array(
             'local' => 'acolhido_id',
             'foreign' => 'id'));

        $this->hasOne('Pai', array(
             'local' => 'pai_id',
             'foreign' => 'id'));

        $this->hasOne('Mae', array(
             'local' => 'mae_id',
             'foreign' => 'id'));

        $this->hasOne('Responsavel', array(
             'local' => 'responsavel_id',
             'foreign' => 'id'));

        $this->hasOne('Voluntario', array(
             'local' => 'voluntario_id',
             'foreign' => 'id'));

        $this->hasOne('Padrinho', array(
             'local' => 'padrinho_id',
             'foreign' => 'id'));
    }
}