<?php

/**
 * BasePessoa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property enum $sexo
 * @property date $dataNascimento
 * 
 * @method string getNome()           Returns the current record's "nome" value
 * @method enum   getSexo()           Returns the current record's "sexo" value
 * @method date   getDataNascimento() Returns the current record's "dataNascimento" value
 * @method Pessoa setNome()           Sets the current record's "nome" value
 * @method Pessoa setSexo()           Sets the current record's "sexo" value
 * @method Pessoa setDataNascimento() Sets the current record's "dataNascimento" value
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Luiz Oliveira
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePessoa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pessoa');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sexo', 'enum', 9, array(
             'type' => 'enum',
             'length' => 9,
             'values' => 
             array(
              0 => 'Masculino',
              1 => 'Feminino',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('dataNascimento', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}