<?php

/**
 * BaseCursoExternoAcolhido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $acolhido_id
 * @property string $nomeCurso
 * @property string $descricao
 * @property string $nomeEscola
 * @property date $dataConclusao
 * @property Acolhido $Acolhido
 * 
 * @method integer              getAcolhidoId()    Returns the current record's "acolhido_id" value
 * @method string               getNomeCurso()     Returns the current record's "nomeCurso" value
 * @method string               getDescricao()     Returns the current record's "descricao" value
 * @method string               getNomeEscola()    Returns the current record's "nomeEscola" value
 * @method date                 getDataConclusao() Returns the current record's "dataConclusao" value
 * @method Acolhido             getAcolhido()      Returns the current record's "Acolhido" value
 * @method CursoExternoAcolhido setAcolhidoId()    Sets the current record's "acolhido_id" value
 * @method CursoExternoAcolhido setNomeCurso()     Sets the current record's "nomeCurso" value
 * @method CursoExternoAcolhido setDescricao()     Sets the current record's "descricao" value
 * @method CursoExternoAcolhido setNomeEscola()    Sets the current record's "nomeEscola" value
 * @method CursoExternoAcolhido setDataConclusao() Sets the current record's "dataConclusao" value
 * @method CursoExternoAcolhido setAcolhido()      Sets the current record's "Acolhido" value
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Luiz Oliveira
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCursoExternoAcolhido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('curso_externo_acolhido');
        $this->hasColumn('acolhido_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nomeCurso', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('nomeEscola', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('dataConclusao', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Acolhido', array(
             'local' => 'acolhido_id',
             'foreign' => 'id'));
    }
}