<?php

/**
 * BasePai
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $AcolhidoPai
 * @property Doctrine_Collection $EntradasESaidasPai
 * 
 * @method Doctrine_Collection getAcolhidoPai()        Returns the current record's "AcolhidoPai" collection
 * @method Doctrine_Collection getEntradasESaidasPai() Returns the current record's "EntradasESaidasPai" collection
 * @method Pai                 setAcolhidoPai()        Sets the current record's "AcolhidoPai" collection
 * @method Pai                 setEntradasESaidasPai() Sets the current record's "EntradasESaidasPai" collection
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Luiz Oliveira
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePai extends Responsavel
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Acolhido as AcolhidoPai', array(
             'local' => 'id',
             'foreign' => 'pai_id'));

        $this->hasMany('EntradasESaidasAcolhido as EntradasESaidasPai', array(
             'local' => 'id',
             'foreign' => 'pai_id'));
    }
}