<?php

/**
 * Acolhido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Acolhido extends BaseAcolhido
{

    public function getSituacao() {

        if ($this->getDataDesligamento() == null) return "Ativo";
        else return "Desligado";

    }

    
    public function getPaiAutorizado() {

        $pai = $this->getPai();
        var_dump($pai);
        if ($pai->getAutorizacaoVisita() == "Sim") return $pai;
        else return null;

    }

    public function __toString() {

        return $this->getNome();

    }


}
