<?php

/**
 * Acolhido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Acolhido extends BaseAcolhido
{

    public function getSituacao() {

        if ($this->getDataDesligamento() == null) return "Ativo";
        else return "Desligado";

    }

    
    public function getPaiAutorizado() {

        $pai = $this->getPai();
        if ($pai->getAutorizacaoVisita() == "Sim") return $pai;
        else return null;

    }

    public function __toString() {

        return $this->getNome();

    }

    /* 
     * Informa se o acolhido está dentro ou fora do abrigo de acordo com os registros de entrada e saída.
    */

    public function isFora() {

        $entradas = $this->getEntradasESaidasAcolhido();
        foreach($entradas as $entrada) {
            if ($entrada->getDataRetorno() == null) return true;
        }
        return false;
    }

}
