<?php

/**
 * EscolaridadeAcolhido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    abrigo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EscolaridadeAcolhido extends BaseEscolaridadeAcolhido
{

    function getAcolhidoNome() {

        return $this->getAcolhido()->getNome();

    }

    function getEscolaridadeNome() {

        return $this->getNivelEscolaridade()->__toString();

    }


}
