<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/28 21:02:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=abrigo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
